### ISSUE TITLE
Default percentages

### ISSUE THREAD

**Issue by rubenvarela** [victoroalvarez/tip#1]
Default percent on slider is set to 18%, https://github.com/victoroalvarez/tip/blob/3e38a657cf0160370effce34d24e78086df165f0/index.html#L36

Default percent shown is 15%, https://github.com/victoroalvarez/tip/blob/3e38a657cf0160370effce34d24e78086df165f0/index.html#L41

One of them just needs to be changed to match the other.

Tip is calculated based on slider value. So, while it shows 15%, it's really using 18% by default.

**Comment by victoroalvarez** [comment]
Thanks. Fixed it now.
